walmart_project:
  outputs:
   dev:
        type: databricks
        catalog: "{{ env_var('DBT_CATALOG', 'walmart') }}"
        host: "{{ env_var('DBT_HOST') }}"
        http_path: "{{ env_var('DBT_HTTP_PATH') }}"
        schema: "{{ env_var('DBT_SCHEMA', 'dbt_schema') }}"
        threads: "{{ env_var('DBT_THREADS', '5') | int }}"
        token: "{{ env_var('DBT_TOKEN') }}"
    target: dev
